services:
  - type: web
    name: whatshouldIeat-backend
    runtime: node
    rootDir: back_end
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 4000
